project:
  type: website

website:
  title: "Andrei Stoica"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cyborg
    css: 
      - tailwind.css
      - styles.css
    toc: true
