project:
  type: website
  output-dir: public

website:
  title: "Andrei Stoica"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About

format:
  html:
    theme: 
      dark: darkly
      light: flatly
    toc: true
    embed-resources: true
    self-contained-math: true
