project:
  type: website
  output-dir: public

website:
  title: "Andrei Stoica"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Projects"
        menu:
          - projects/nlp-queries.qmd 
          - projects/open-data-graph.qmd 
          - projects/cdn-poli.qmd 
      - href: about.qmd
        text: About
      - href: posts.qmd
        text: Posts


format:
  html:
    theme: darkly
    toc: true
    embed-resources: true
    self-contained-math: true
