project:
  type: website
  output-dir: public

website:
  title: "Andrei Stoica"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cyborg
    css: 
      - tailwind.css
      - styles.css
    toc: true
    embed-resources: true
    self-contained-math: true
