---
title: "Andrei Stoica"
about:
  template: solana
  id: hero
  links:
    - icon: github
      text: Github
      href: https://www.github.com/andrei-stoica
    - icon: linkedin
      text: LinkedIn
      href: https://www.linkedin.com/in/andrei-stoica
citation-location: margin
bibliography: papers.bibtex
---

<br />


:::{#hero}

### Education

**Master of Science** - Computer Science | Ontario Tech University <br />
2022 | Oshawa, ON 

**Bachelor of Science** - Computer Science | Ontario Tech University <br />
2018 | Oshawa, ON

:::

### Work Experience

**Data Engineer (contract)** | The Block Crypto <br />
Aug. 2022 - April 2023 | New York, NY

- build data pipelines that extract data from 16 exchanges (**Airflow**)
- clean data from api and normalize currency (**Pandas**)
- warhouse data on **AWS** (**S3**, **Redshift**)
- colaborate with research team to eusure data quality
- on call for unexpected pipeline failures

**Graduate Research Assistant** | Ontario Tech University <br />
May 2018 - Aug. 2020 | Oshawa, ON

- NLP Relational Queries And Its Applications
  - *Something Goes here*
- Scalable Analysis of Open Data Graphs
  - *Something Goes here*
- Canadian Political Twitter Analysis
  - track public sentiment toward political parties
  - ingetst tweets via twitter api
  - stream tweets that mention party members
  - data storage via PostgreSQL
  - *Something about visualization goes here*

---

- CDNPoli
  + ingest data via twitter api
  + stream tweets that mention party members 
    * calculate sentiment of tweets (TF, sk-learn)
  + datastore via PostgreSQL
- OpenDataGraph
  + GCP Dataproc(Spark)
  + pyspark
  + distributed compute to analyze similarity graph
  + large open dataset
- NLP/SQL
  + perform opperations for NLP in PostgreSQL:
    * perform text normalization
    * perform tokenization
    * text embeding
    * similarity of documents



### Project Experience

**NLP Relational Queries And Its Applications** [-@2020] *Thesis Project* 

- Developed LDA extension to PostgreSQL to allow Topic Modelling of text
  columns inside of SQL
- Created a web front end to visualize the change in topics over time for
  academic authors and venues
- Published 2020 IEEE International Conference on Information Reuse and
  Integration for Data Science 
- Technologies : **Python** · **SQL/PostgreSQL** · **Flask** ·
                 **HTML** · **CSS** · **D3.js**

**Scalable Analysis of Open Data Graphs** [-@2019]

- Performed analysis of similarities between documents through
  Canada’s Open Data portal
- Provided insight into organization and connectedness of Canada’s Open Data
- Scalable and Distributed code base to allow for large dataset and
  scaling with time
- Published and Presented at 2019 IEEE International Conference on Information
  Reuse and Integration for Data Science 
- Technologies : **Python** · **SQL/PostgreSQL** · **Apache** ·
                 **Spark/PySpark** · **Matplotlib** ·
                 **GCP Storage** · **GCP Dataproc**

**Canadian Political Twitter Analysis**

- Built tools to track and analyse the conversation surrounding
  Canadian politics on Twitter
- Tracked key figures and CDNPoli hashtag and predicted standings in
  2019 election
- Technologies : **Python** · **Tensorflow** ·
                 **SQL/PostgreSQL** · **Matplotlib**

